config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  root :to => "static_pages#index", :id => '1'
  get 'static_pages/secret'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participation.rb
class Participation < ApplicationRecord
	belongs_to :user
	belongs_to :party 
end

app/models/party.rb
class Party < ApplicationRecord
  after_create :new_participation

  def new_participation
    EventMailer.new_participation(self).deliver_now
  end

  validates :start_date,
    presence: true
    validate :in_the_past?
  validates :duration,
    presence: true,
    numericality: { greater_than_or_equal_to: 5 }
    validate :multiple_of_5?
  validates :title,
    presence: true,
    length: { in: 5..140 }
  validates :description,
    presence: true,
    length: { in: 20..1000 }
  validates :price,
    presence: true,
    length: { in: 1..1000 }
  validates :location,
    presence: true

  has_many :participations
  has_many :users, through: :participations
  belongs_to :user

  private

  def multiple_of_5?
    return duration unless duration % 5 != 0 || duration.negative?
      errors.add(
        :duration,
        'The duration must end by 0 ou 5 and be a positive number.'
      )
  end

  def in_the_past?
    return start_date unless start_date < Time.now
      errors.add(:start_date, 'The start date cannot be in the past!')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :participations
	has_many :parties, through: :participations
	
	#after_create :welcome_send
 	def welcome_send
    UserMailer.welcome_email(self).deliver_now
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def secret
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Eventbrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= static_pages_index_path %>">Accueil<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Créer un évènement</a>
      </li>
     
      <li class="nav-item">
        <a class="nav-link" href=" <%= new_user_registration_path %>">S'inscrire</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <button class="btn btn-outline-success my-2 my-sm-0" href="<%= user_session_path %> type="submit">Se connecter</button>
    </form>
  </div>
</nav>


    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>